<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mahesh_PC" failures="4" tests="26" name="runner.TestRunner" time="14.881" errors="0" timestamp="2024-10-18T13:25:45 CDT" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="0.354"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.359"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.257"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.351"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.431"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.232"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.535"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.428"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.355"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.352"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.400"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.361"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.409"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.353"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.455"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.358"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.364"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.426"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.445">
    <failure message="expected [201] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [500]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at stepDefinitions.createUserSteps.userShouldReceiveAValidResponse(createUserSteps.java:40)
at ✽.The response status code should be 201 Created(file:///C:/Users/manal_/git/UserAPIOct24/UserAPIProject/src/test/resources/features/01CreateUser.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.245">
    <failure message="expected [404] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [500]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at stepDefinitions.getUserByIDSteps.the_response_status_code_should_be_not_found(getUserByIDSteps.java:102)
at ✽.The response status code should be 404 Not Found(file:///C:/Users/manal_/git/UserAPIOct24/UserAPIProject/src/test/resources/features/03GetUser.feature:47)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.572"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.392"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.407"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.352"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.455">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at stepDefinitions.createUserSteps.userShouldReceiveAValidResponse(createUserSteps.java:40)
at ✽.The response status code should be 201 Created(file:///C:/Users/manal_/git/UserAPIOct24/UserAPIProject/src/test/resources/features/01CreateUser.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="0.233">
    <failure message="expected [400] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at stepDefinitions.deleteUserByIDSteps.user_Notdeleted_status(deleteUserByIDSteps.java:53)
at ✽.The status code should be 400 Bad Request(file:///C:/Users/manal_/git/UserAPIOct24/UserAPIProject/src/test/resources/features/04DeleteUser.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
